name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/uuidgen-t:latest
          platforms: 'amd64,arm64'
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Notify container release
        uses: SimonScholz/google-chat-action@main
        with:
            webhookUrl: '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}'
            title: "🐳📦🔀 ${{ secrets.DOCKERHUB_USERNAME }}/uuidgen-t"
            subtitle: "Nueva imagen disponible en Docker Hub."
            createDefaultSection: false
